### ISSUE TITLE
ReSwift 5.0 Release Plan

### ISSUE THREAD

**Issue by DivineDominion** [ReSwift/ReSwift#303]
Here's what I found in the issues and current PRs. Please add and discuss.

I also created a GitHub project from this list, in case that makes contributing to the roadmap any easier: <https://github.com/ReSwift/ReSwift/projects/1>

------

### Low-Hanging Fruit:

- [x] Fix memory leaks, see #302 
- [x] Finish up PR #300 as a fix #298
- [x] Approve #295 
- [x] ~Review #231 (generic `ActionCreator`); it is missing an `AsyncActionCreator` counterpart~ `ActionCreator` will be deprecated in favor of `ReSwift-Thunk` in the future

### Breaking Changes

- [x] Perform making state setter private as per #264 (breaking API change, bump to 5.0?)
    - [x] Deprecate ReSwiftRecorder, make outdated dependency on v3.x transparent in the README, look for new maintainers in the community?

### Consider including

- [ ] ~Avoid double equatability checks, as per failing #259, needing a fix~ (deferred to post 5.0)

### Release Preparation

(Done manually, because #248 never got implemented :))

- [x] Update docs
- [x] Collect contributions for the release notes
- [x] Update README

**Comment by danielmartinprieto** [comment]
This is great!

Regarding https://github.com/ReSwift/ReSwift/pull/231, I know that you guys put some time on it and also that there are some open issues related that got nowhere, but I'd like to ask you to revisit it, because I really think that the `ActionCreator` and `AsyncActionCreator` types are confusing and somewhat misleading, and I think they shouldn't belong to the core ReSwift project.

About `ActionCreator`s, everything that gives you an instance of a type conforming `Action` could be called "action creator".

On the other hand, there are different, more idiomatic ways of handling asynchronous operations in ReSwift (using the middleware layer, for instance). The ability of dispatching a thunk is more like an extension (that can follow different approaches, as we've already seen in this repo, with some implementations attempts), and therefore I wouldn't include any of them here.

What do you think? Please, note that I'm totally fine if you don't agree with me here, I just think that the simplification of removing it from ReSwift would be worth it.

**Comment by DivineDominion** [comment]
I don't use action creators at all, so I don't see their value given how ReSwift works (nowadays) :) Hate to put the load on @Ben-G, but he's probably the best to answer. (Discussion started in #150)

**Comment by mjarvis** [comment]
`4.0` is the currently released version -- should this be `4.1` or `5.0` release planning?

As for release notes, we have been collecting changes in https://github.com/ReSwift/ReSwift/blob/master/CHANGELOG.md though it probably needs reviewing to see if things have been missed.

**Comment by DivineDominion** [comment]
Whoops, you're right. Since we have some breaking API changes, maybe a major version bump would communicate the change more clearly.

**Comment by JoeCherry** [comment]
#300 should be ready for a review when someone gets a chance.

**Comment by blazierkyle** [comment]
@danielmartinprieto I am curious about your comments on `ActionCreator`s. I’m relatively new to Redux and ReSwift but have been using `AsyncActionCreator`s in my current project. From my perspective, this was a nice way to handle Async requests that ultimately fire actions, and it makes it extremely clear while reading code where actions are dispatched when making Async requests- for example:

```
store.dispatch(
	UserProfileActionCreator.getUserDetails()
)
```

On a somewhat related note, I’ve seen the suggestion to use ActionCreators instead of AsyncActionCreators, like in Ben-G’s implementation of the TwitterAPIActionCreator (https://github.com/Ben-G/Meet/blob/master/Meet/Meet/Actions/TwitterAPIActionCreator.swift#L58) and I must say I find it a little confusing. While I can understand this this is technically an ActionCreator since an action is created from the result of this function, it seems unintuitive to me since this function will effectively always return nil. By contrast, I like the idea of AsyncActionCreators where you clearly return the action you want to be dispatched, or nil if you do not want to dispatch any actions.

I do really like #231 and think it makes ActionCreators cleaner.

I’d be happy to engage in a discussion on this and see how Async actions could be handled with middleware as mentioned above!

**Comment by danielmartinprieto** [comment]
All right, I will create a playground showing how I use middleware for async stuff tonight! I’ll try to explain as well why I think `ActionCreator` and `AsyncActionCreator` are not needed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ben-G** [comment]
Looking forward to the playground. I’m currently traveling but following this thread :)

**Comment by danielmartinprieto** [comment]
Hi, all. Here is the playground, as promised. Let me know what you think!

https://gist.github.com/danielmartinprieto/c571ada2cf065b32e5c3d6eda3f8c06a

**Comment by danielmartinprieto** [comment]
Hey, @blazierkyle & @Ben-G, have you had time to take a look at it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by blazierkyle** [comment]
Hi @danielmartinprieto - thanks for putting together that playground, I appreciate you taking the time especially to go into detail with your comments! My apologies on the delayed response, I’ve spent some time thinking this over and discussing with some colleagues.

As far as my thoughts on using middleware vs AsyncActionCreators, I have several thoughts. I find that there are pros and cons to each of the two solutions. For middleware, I like the separation of concerns where you could architect your app in a way such that only the middleware knows about your API. Additionally, I like the ability to dispatch multiple actions, vs ActionCreators where you can only return one action. I also feel that making async requests in middleware in response to actions can be very useful in certain scenarios, but is not always desirable. 

My biggest concern is that, from my perspective, middleware should be a place to handle only side effects, like logging or capturing analytics, not dispatching actions that update the state, which is most certainly not a side effect. In addition, I find the syntax of middleware functions in general to be verbose and difficult to read/learn.

That being said, I still feel that AsyncActionCreators have a use in ReSwift. I feel like when discussing removing action creators, the lines between `ActionCreators` and `AsyncActionCreators` are blurred, which I would really like to emphasize. I suspect that many of the opinions against action creators are truly more against the synchronous `ActionCreators`, since there use is limited and almost confusing in terms of when they should be used. On the contrary, I find `AsyncActionCreators` very useful for making async requests and their syntax is much more clear (and Swifty). 

I want to be clear that I’m not suggesting here that AsyncActionCreators should be documented as the #1 way to handle async requests with ReSwift, but should be kept in the library as an option (and documented).

Again, thanks for taking the time to put together the playground and I look forward to discussing further!

**Comment by danielmartinprieto** [comment]
Thanks to you for taking the time of checking it and coming back with the feedback!

> I also feel that making async requests in middleware in response to actions can be very useful in certain scenarios, but is not always desirable.

Could you share a couple of examples where it's not desirable? I can't come with one myself and I'd love to understand better the trade offs of my approach.

> My biggest concern is that, from my perspective, middleware should be a place to handle only side effects, like logging or capturing analytics, not dispatching actions that update the state, which is most certainly not a side effect.

I disagree here. I consider everything that is not a direct change of the state (via reducers) a side effect, including new dispatches. Example: let's imagine that you have a balance in a bank account and you perform a withdrawal. Upon success, you will want to reload the balance. For me, that's a side effect of the `WithdrawalSuccess` action. Also, the middleware API gives you the possibility of dispatching actions, so it's clearly one of its responsibilities.

Anyway, I can understand how convenient could be having a general way of dispatching a set of actions asynchronously without the need to set up a middleware for it, even if I don't use if myself because of the reasons I shared in the playground. That's why, as a convenience/helpful tool (and not a core type) I would put it in a separate framework, reducing the confusion and simplifying the ReSwift API.

**Comment by DivineDominion** [comment]
So @danielmartinprieto proposal, as I understand it: 

**Extract anything dispatchable that's more complex than the `Action` protocol itself into ReSwift userland, out of the core.** (I wonder if a distinction similar to RxSwift (core) and RxCocoa (UI and app programming helpers) could make sense, although I don't know what that may entail, yet.)

## On Side Effects

I see how you disagree about "side effect". I have a hunch that "side effect" used to mean anything that leaves the app, like touching the file system; with functional programming paradigms on the rise, "side effect" is becoming more closely akin to "anything that's not part of a pure function". A reducer is supposed to be a pure function: `(State, Action)` in, `State` out. 

To clarify how the strict sense applies (and lifting the topic from opinion to argument): The dispatch method of `Store` is a command with side effects: middleware + store subscribers are affected with unknown and maybe unrepeatable results, and the `state` property is mutated. Consequently, any function that dispatches an action is in turn having side-effects, too.

**Comment by danielmartinprieto** [comment]
Yes, I think the RxSwift & RxCocoa distinction is a good example of a core library + additions.

I'd argue that doing this simplifications (not only in this particular case, but in general) is good for this kind of libraries. It helps you focus on the main concepts that motivate them, a good API that can be used to build things on top, and a performant, bug free implementation.

I want to point out that this exact discussion has been happening in the original Redux ecosystem as well. The core Redux library allows you to dispatch only plain actions. Later, [redux-thunk](https://github.com/gaearon/redux-thunk) was born, created by the same person as Redux, where you can dispatch functions that take the store's `getState` and `dispatch` functions as parameters, allowing you to perform async operations (note how this is implemented using a small, simple middleware). After that, several other libraries have been created, using different concepts and paradigms ([redux-saga](https://github.com/redux-saga/redux-saga), [redux-loop](https://github.com/redux-loop/redux-loop), [redux-observable](https://redux-observable.js.org/), etc.), all of them on top of the original Redux core library.

**Comment by amreshkumar** [comment]
Hi Guys, We are having some really good discussion here but given the release checklist - i'm sure it is going to take some time to get 4.1/5.0 released. Do you think it makes sense to get a 4.0.1 release out with whatever updates we have - and to push major/breaking changes to 4.1/5.0 ? I'm more concerned about the memory leaks issue because it is definitely stopping people from using ReSwift on large scale in production.

**Comment by DivineDominion** [comment]
Yeah, moving the discussion to a 5.0 target sounds reasonable to me. Sadly, there's not a lot of moderating/splitting/moving comments I can do, so the best thing we have is an additional 5.0 checklist :)

**Comment by Ben-G** [comment]
@DivineDominion how about we release the current `master` branch now-ish to resolve the memory leak issue? I agree with @amreshkumar that it should be part of a release ASAP. Since `master` includes breaking changes this would need to be a 5.0.0 release. But I personally don't mind making major releases frequently. This way we can have the other discussions listed above, without time pressure.

Thoughts?

**Comment by danielmartinprieto** [comment]
Yeah, I’d say the memory leak and the skip repeats issues should be released soon.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mjarvis** [comment]
If it makes things go faster we could branch off the last release and cherry pick the bug fixes, and release as 4.0.1, then that gives more time to figure out the plan for the features / breaking changes

**Comment by mjarvis** [comment]
I've branched off the `4.0.0` tag and created https://github.com/ReSwift/ReSwift/tree/mjarvis/4.0.1 In which I've cherry-picked the two important bug fixes, and update the version specifications appropriately.

I've also created a draft release at https://github.com/ReSwift/ReSwift/releases/tag/untagged-f47ec39b635d493d988a
From here I'll leave it up to either @Ben-G or @agentk to review & release, since they're the ones with CocoaPods trunk access.

**Comment by danielmartinprieto** [comment]
I think #300 should be included as well, fixing #298.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ben-G** [comment]
@mjarvis Do you want to follow @danielmartinprieto suggestion and include #300?

**Comment by mjarvis** [comment]
I've cherry-picked #300 into https://github.com/ReSwift/ReSwift/releases/tag/untagged-f47ec39b635d493d988a and updated the changelog & release notes as appropriate.
It would be beneficial for @JoeCherry to do a quick review of my cherry-pick since there were some conflicts due to some new features not being in that branch.

**Comment by mjarvis** [comment]
[4.0.1](https://github.com/ReSwift/ReSwift/releases/tag/4.0.1) has been released.
I'll make a PR to get master's changelog updated later today.

**Comment by DivineDominion** [comment]
Thanks a ton for the effort you poured into releasing this!

**Comment by mjarvis** [comment]
@DivineDominion @danielmartinprieto Given the amount of time since the last release, and the lack of updates lately, how do you feel about release 5.0 as-is? I feel like there are enough changes to warrant it.

**Comment by danielmartinprieto** [comment]
Mmm, I think 5.0 is a pretty nice number to do the breaking change of the `ActionCreator` and `AsyncActionCreator`. We can release a 4.something with the deprecation warning, and the 5.0 with the breaking change.

**Comment by mjarvis** [comment]
I suppose I should back-branch and also deprecate `StandardAction` and `StandardActionConvertible` for a 4.1 release?

**Comment by danielmartinprieto** [comment]
I was not aware of those, but I guess if someone wants to build middlewares that use a certain pattern like a standard action or a serializable action, they can do it in userland, as we’ve done with ReSwift-Thunk!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DivineDominion** [comment]
I'd favor a 4-point release with the current changes, then we fix the double equality check for 5.0. I also collected a couple of links that could help me with the rewrite of #307, but I'm stuck coding for my life at the moment, so I can't work on the implementation right now :/

**Comment by sjmueller** [comment]
Are you guys aware that `automaticallySkipsRepeats` is broken on master? It works on `4.0.1`. I have to add `.skipRepeats()` manually on all of my subscriptions to get the desired behavior:
``` swift
store.subscribe(self) { $0.select { $0.camera.playback }.skipRepeats() }
```

**Comment by DivineDominion** [comment]
@sjmueller [we changed the default to false](https://github.com/ReSwift/ReSwift/commit/8b0776ccf0140950252e5c213bd27c1af59cbe29), do you mean that or does setting it to `true` doesn't work for you?

**Comment by sjmueller** [comment]
@DivineDominion correct, I have explicitly set:
``` swift
let store = Store(
    reducer: appReducer,
    state: AppState(),
    middleware: [thunksMiddleware],
    automaticallySkipsRepeats: true
)
```
And here's the result of printing within a `newState` subscription for a simple vanilla enum (notice all the repeats):

<img src="https://user-images.githubusercontent.com/29085/52503042-37f05a00-2b99-11e9-9ec7-cc05a114538f.png" width="200" />

Reverting carthage from `github "ReSwift/ReSwift" "master"` to `github "ReSwift/ReSwift"` brings in 4.0.1, and with no code changes (except for removing `automaticallySkipsRepeats` since it isn't an available param) here's the logs:

<img src="https://user-images.githubusercontent.com/29085/52503374-370bf800-2b9a-11e9-953b-6215b991a8f9.png" width="200" />

Should I file this as a separate issue? Didn't mean to hijack this thread, but also wanted to make sure there was awareness if a new release was imminent.

Also, as a developer with heavy react-native + redux experience, I'd strongly recommend that the default should remain `automaticallySkipsRepeats = true`. This is almost always the desired functionality in a production app, and having an inverse escape hatch e.g. `$0.select { $0.somethingSpecific }.allowRepeats()` would handle the edge cases.

**Comment by mjarvis** [comment]
@sjmueller Definitely raise this in a separate issue.

**Comment by mjarvis** [comment]
Given the amount of time without movement on this, I suggest we release 5.0 as-is. It contains all the major tickets mentioned here, and #259 can be deferred to later release.

**Comment by DivineDominion** [comment]
Yeah, I think you're right. v4.0 was way back in 2017, by the way! :) I'll open a new branch with changes to the docs and all so y'all can proof-read. Anything else that needs attention which is not on the checklist at the top?
